### ISSUE TITLE
There are strings not usable in translations

### ISSUE THREAD

**Issue by IvanRybakov** [aleckrh/laravel-sb-admin-2#10]
There are strings not usable in translations like "Friends" in the line 
https://github.com/aleckrh/laravel-sb-admin-2/blob/41a79424f773b1c20a19e52c0405799363c83741/resources/views/profile.blade.php#L40

**Comment by aleckrh** [comment]
Hello.
This is just a template - you're not really supposed to just use it as-is. If you need a translation you must do it manually for your project.
