### ISSUE TITLE
File structure

### ISSUE THREAD

**Issue by tonywtrd** [aleckrh/laravel-sb-admin-2#17]
I think file structure are not updated as Models is inside App\ where is should be in App\Models\

And there's no \Databases\Seeders\ folder so the process of make a new seeders actually use Laravel 5-.

i suggest an update for file structure as it can be frustrating while change template to this one :)

**Comment by aleckrh** [comment]
Hi, sorry for delay. Thanks for your suggestion, I made some changes.

Kind regards
